### PR TITLE
Extract props to enable i18n...

### PR DESCRIPTION
**Pull request by ahennr**
...for `Style`, `Rule` and `ScaleDenominator` components.

Plz review.

### CODE REVIEW

**Comment by KaiVolland** [comment]
Great feature but the render methods kinda looking awkward now. Seems like this is a price we have to pay for it. We *could* think about something like `ruleProps`, `filterProps`, … which would reduce the tons of props passed in the render method to `{...ruleProps}`…

Did you provide a defaultProp for every required prop?

**Comment by ahennr** [comment]
`defaultProps` are not needed IMHO for the most props, since mostly these are defined in the corresponding components

**Comment by ahennr** [comment]
An example for using `Style` component and i18n looks like 
```
<Style
  style={gsStyle}
  data={internalDataDef}
  onStyleChange={style => this.setState({style})}
  nameFieldLabel={t('Styler.styleNameFieldLabel')}
  nameFieldPlaceholder={t('Styler.styleNameFieldPlaceholder')}
  removeRuleBtnText={t('Styler.removeRuleBtnText')}
  filterFieldSetTitle={t('Styler.filterFieldSetTitle')}
  scaleFieldSetTitle={t('Styler.scaleFieldSetTitle')}
  addRuleBtnText={t('Styler.addRuleBtnText')}
  filterUiProps={{
    attributeLabel: t('AttributeFilterPanel.attributeLabel'),
    attributePlaceholderString: t('AttributeFilterPanel.attributePlaceholderString'),
    attributeValidationHelpString: t('AttributeFilterPanel.attributeValidationHelpString'),
    operatorLabel: t('AttributeFilterPanel.comperatorLabel'),
    operatorPlaceholderString: t('AttributeFilterPanel.comperatorPlaceholderString'),
    operatorValidationHelpString: t('AttributeFilterPanel.operatorValidationHelpString'),
    valueLabel: t('AttributeFilterPanel.valueLabel'),
    valueValidationHelpString: t('AttributeFilterPanel.valueValidationHelpString')
  }}
  ruleNameProps={{
    label: t('Styler.ruleNameFieldLabelText'),
    placeholder: t('Styler.ruleNameFieldPlaceholder')
  }}
  scaleDenominatorProps={{
    minScaleDenominatorLabelText: t('Styler.minScaleDenominatorLabelText'),
    maxScaleDenominatorLabelText: t('Styler.maxScaleDenominatorLabelText'),
    minScaleDenominatorPlaceholderText: t('Styler.minScaleDenominatorPlaceholderText'),
    maxScaleDenominatorPlaceholderText: t('Styler.maxScaleDenominatorPlaceholderText'),
  }}
  previewProps={{
    dataProjection: 'EPSG:3857',
    openEditorText: t('Styler.previewOpenSymbolizerEditorText'),
    closeEditorText: t('Styler.previewCloseSymbolizerEditorText'),
    kindLabelText: t('Styler.kindLabelText'),
    circleEditorProps: {
      radiusLabel: t('Styler.radiusLabel'),
      fillOpacityLabel: t('Styler.fillOpacityLabel'),
      fillColorLabel: t('Styler.fillColorLabel'),
      strokeColorLabel: t('Styler.strokeColorLabel'),
      strokeWidthLabel: t('Styler.strokeWidthLabel'),
      strokeOpacityLabel: t('Styler.strokeOpacityLabel')
    },
    fillEditorProps: {
      fillOpacityLabel: t('Styler.fillOpacityLabel'),
      fillColorLabel: t('Styler.fillColorLabel'),
      outlineColorLabel: t('Styler.outlineColorLabel')
    },
    iconEditorProps: {
      imageLabel: t('Styler.imageLabel'),
      opacityLabel: t('Styler.opacityLabel'),
      rotateLabel: t('Styler.rotateLabel'),
      sizeLabel: t('Styler.sizeLabel'),
      defaultIconSource: t('Styler.defaultIconSource')
    },
    lineEditorProps: {
      colorLabel: t('Styler.strokeColorLabel'),
      widthLabel: t('Styler.strokeWidthLabel'),
      opacityLabel: t('Styler.strokeOpacityLabel'),
      dashLabel: t('Styler.dashLabel')
    },
    textEditorProps: {
      fieldLabel: t('Styler.fieldLabel'),
      opacityLabel: t('Styler.opacityLabel'),
      colorLabel: t('Styler.colorLabel'),
      sizeLabel: t('Styler.sizeLabel'),
      offsetXLabel: t('Styler.offsetXLabel'),
      offsetYLabel: t('Styler.offsetYLabel'),
      fontLabel: t('Styler.fontLabel')
    }
  }}
/>
``` 
where `t` is a function returning the translated text for passed key.

**Comment by ahennr** [comment]
:top: thx for review

**Pull request merged**
