### PR TITLE
Fix ci pipeline

### PR DESCRIPTION
**Pull request by KaiVolland**
This makes the shell script executable.
Compare the git file permission number in the diff.

### CODE REVIEW

**Comment by chrismayer** [comment]
Executable seems a good idea for a script we wanna execute... :wink:

**Comment by marcjansen** [comment]
I'll merge to see what happens :crossed_fingers:

**Comment by marcjansen** [comment]
> Seems to work now. At least for "latest".

No sadly it still doesn't. The commit on the `gh_pages` branch was done manually by me, not via Travis.

> Maybe i can fix some bug today, so we can make a new release.

Yeah, do that

**Comment by marcjansen** [comment]
Can we please evaluate whetehr we can use [`gh-pages`](https://www.npmjs.com/package/gh-pages), which we use elsewhere?

**Comment by KaiVolland** [comment]
I'll give it a try.

**Pull request merged**
