### PR TITLE
Fix minors in the update-gh-pages script

### PR DESCRIPTION
**Pull request by marcjansen**
This makes the script run locally when I mockup several of the environment variables of Travis. See e.g. this commit on the `gh_pages`-branch: https://github.com/terrestris/geostyler/commit/1b8ea31c2d48c8d016b6982e5636accd20b63c3a

The docs do not look as if much changed, as we have to list the sections for each component manually… do I understand this correctly? If so, what other otions do we have?

However, the changes herein are separate, and I think these fix the docs autgeneration and publishing.

Please review.

### CODE REVIEW

**Comment by chrismayer** [comment]
Thanks for this @marcjansen. 

I am quite unsure why there is a commit of me in the gh-pages branch around 2 hours ago.
To test if everything is working fine we should see a folder for the version tag next time we release, right?

**Comment by marcjansen** [comment]
> Thanks for this @marcjansen.
> 
> I am quite unsure why there is a commit of me in the gh-pages branch around 2 hours ago.

That is because I was taking your identity as the `update-gh-pages`-script does :smile: 

> To test if everything is working fine we should see a folder for the version tag next time we release, right?

Hopefully.

**Comment by marcjansen** [comment]
For reference, here is a bash script that makes the `update-gh-pages.sh` execute locally as if being run on travis, just put in a script at the repo's root:

```bash
#!/usr/bin/env bash

npm install

npm run test:ci

npm run build

export TRAVIS=true
export TRAVIS_PULL_REQUEST=false
export TRAVIS_BRANCH=master
export TRAVIS_NODE_VERSION=12
export TRAVIS_COMMIT=`git rev-parse HEAD`
export GH_TOKEN=YOU-HAVE-TO-USE-YOUR-OWN
export TRAVIS_BUILD_DIR=`pwd`

source .ci/update-gh-pages.sh

git config --global user.name "First Last" # adjust, important, because the other script changes this !!!
git config --global user.email "info@example.com" # adjust, important, because the other script changes this !!!
```

**Comment by chrismayer** [comment]
> > Thanks for this @marcjansen.
> >I am quite unsure why there is a commit of me in the gh-pages branch around 2 hours ago.

> That is because I was taking your identity as the update-gh-pages-script does smile

SCANDAL! :open_mouth: :wink: 

>> To test if everything is working fine we should see a folder for the version tag next time we release, right?

> Hopefully.

Would you like to release a patch release? Then we would have a clear picture.

**Comment by marcjansen** [comment]
> Would you like to release a patch release? Then we would have a clear picture.

I can try, never did it in this repo :grimacing:

**Comment by chrismayer** [comment]
Execute `npm run release` The rest is done interactively in the command line. If you are unsure I can do this.

**Comment by marcjansen** [comment]
> Execute `npm run release` The rest is done interactively in the command line. If you are unsure I can do this.

Thnaks, I fear right now the script still isn't doing everything correctly

**Pull request merged**
