### PR TITLE
Fix crash if text symbolizer has no label set

### PR DESCRIPTION
**Pull request by hwbllmnn**
@terrestris/devs Please review.

### CODE REVIEW

**Comment by hwbllmnn** [comment]
Using `value` instead of `defaultValue` causes the label field not being editable any more. BTW, do you have any idea why CI is failing? The build works just fine for me locally.

**Comment by KaiVolland** [comment]
> Using `value` instead of `defaultValue` causes the label field not being editable any more. BTW, do you have any idea why CI is failing? The build works just fine for me locally.

Hmm that's strange. Works like this for every other antd component.
> BTW, do you have any idea why CI is failing? The build works just fine for me locally.
I'll have a look.

**Comment by KaiVolland** [comment]
Maybe the recent package updates have caused another occasion of mixed `@types` packages...

**Comment by KaiVolland** [comment]
The types need to stay in the `dependencies` so `"types": "dist/index.d.ts"` brings all the types to the user.

**Comment by hwbllmnn** [comment]
It seems the failures were caused by the `@types` being split between `devDependencies` and `dependencies`. Moving them all to `dependencies` fixes the problem.

**Comment by KaiVolland** [comment]
Still strange. We should keep an eye on this.

Could you try to keep the definietly testing realted packages in the `devDependencies`?
```js
"@types/enzyme": "3.9.1",
"@types/jest": "24.0.11",
"@types/jest-diff": "20.0.1",
"@types/node": "11.11.6"
```
If you still got issues, feel free to merge anyway. We should have an eye on this, especially regarding to new antd releases.

**Comment by hwbllmnn** [comment]
Squash-merged.

**Pull request merged**
